name: Build and Test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      MYSQL_USER: planka
      MYSQL_PASSWORD: planka
      MYSQL_DATABASE: planka
      MYSQL_PORT: 3306

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: ${{ env.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ env.MYSQL_PASSWORD }}
          MYSQL_DATABASE: ${{ env.MYSQL_DATABASE }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: client/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('client/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies and build client
        run: |
          npm install
          cd client
          npm run build

      - name: Set up and start server for testing
        env:
          DEFAULT_ADMIN_EMAIL: demo@demo.demo
          DEFAULT_ADMIN_PASSWORD: demo
          DEFAULT_ADMIN_NAME: Demo Demo
          DEFAULT_ADMIN_USERNAME: demo
          MYSQL_HOST: 127.0.0.1
          MYSQL_PORT: 3306
          MYSQL_USER: planka
          MYSQL_PASSWORD: planka
          MYSQL_DATABASE: planka
        run: |
          client/tests/setup-symlinks.sh
          cd server
          cp .env.example .env
          npm run db:init
          npm start --prod &

      - name: Wait for server to start
        run: |
          sudo apt-get update
          sudo apt-get install -y default-mysql-client wait-for-it
          wait-for-it -h 127.0.0.1 -p 1337 -t 10

      - name: Seed database with terms signature
        run: |
          TERMS_SIGNATURE=$(sha256sum terms/_template/en-US.md | awk '{print $1}')
          mysql -h 127.0.0.1 -P 3306 -u $MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE -e "UPDATE user_account SET terms_signature = '$TERMS_SIGNATURE';"
        working-directory: ./server

      - name: Run UI tests
        run: |
          npx playwright install chromium
          npm run test:acceptance
        working-directory: ./client
